### ISSUE TITLE
facade doesn't match es-module-lexer

### ISSUE THREAD

**Issue by iAmNathanJ** [fz6m/rs-module-lexer#1]
### Describe the bug

It looks like the `facade` property does not match the output of `es-module-lexer`. Is that intentional?

I noticed tests for facade are disabled in `equal.ts`.

### Reproduction

https://runkit.com/iamnathanj/runkit-npm-rs-module-lexer

### System Info

```Shell
System:
    OS: macOS 13.5.2
    CPU: (8) arm64 Apple M1 Pro
    Memory: 232.45 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.12.0 - ~/.nvm/versions/node/v16.12.0/bin/node
    Yarn: 1.22.18 - ~/.nvm/versions/node/v16.12.0/bin/yarn
    npm: 8.1.0 - ~/.nvm/versions/node/v16.12.0/bin/npm
  Browsers:
    Chrome: 118.0.5993.117
    Safari: 16.6
    Safari Technology Preview: 17.0
```

### Used Package Manager

npm

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by fz6m** [comment]
Fixed in `v2.0.1`

**Comment by iAmNathanJ** [comment]
Incredible. Much appreciated! 🙏🏻

**Comment by developit** [comment]
@fz6m  ありがとうございます
