### ISSUE TITLE
Wasm build

### ISSUE THREAD

**Issue by marvinhagemeister** [fz6m/rs-module-lexer#2]
### Clear and concise description of the problem

I'm looking at running `rs-module-lexer` inside an edge function, but noticed that there doesn't seem to be a wasm variant available. I can only find native binaries.

### Suggested solution

Add a wasm build of `rs-module-lexer`

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by fz6m** [comment]
Release in [v2.1.1](https://github.com/fz6m/rs-module-lexer/releases/tag/v2.1.1)

**Comment by marvinhagemeister** [comment]
Sweet, thank you so much ❤️
