### ISSUE TITLE
facade doesn't match es-module-lexer for type exports

### ISSUE THREAD

**Issue by MitchLillie** [fz6m/rs-module-lexer#6]
### Describe the bug

I'm seeing different behavior between es-module-lexer and rs-module-lexer for the following code:

```ts
export interface MyInterface {
  value: string;
}
```

Possibly related to [an earlier issue](https://github.com/fz6m/rs-module-lexer/issues/1) that was fixed.

### Reproduction

https://runkit.com/mitchlillie/runkit-npm-rs-module-lexer

### System Info

```Shell
System:
    OS: Linux 6.5 Ubuntu 22.04.4 LTS 22.04.4 LTS (Jammy Jellyfish)
    CPU: (8) x64 Intel(R) Xeon(R) CPU @ 2.60GHz
    Memory: 22.69 GB / 62.79 GB
    Container: Yes
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 20.11.1 - ~/.nvm/versions/node/v20.11.1/bin/node
    npm: 10.2.4 - ~/.nvm/versions/node/v20.11.1/bin/npm
    pnpm: 8.15.5 - ~/.dev/pnpm/8.15.5/pnpm
    Watchman: 4.9.0 - /usr/bin/watchman
```

### Used Package Manager

pnpm

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by fz6m** [comment]
The `es-module-lexer` does not support parsing TS syntax. after compilation, this code equals an empty string, so their parsing results are the same:

```ts
import { strictEqual } from 'node:assert'

import { parse } from 'rs-module-lexer'
import { init, parse as esParse } from 'es-module-lexer'

const sample = `
export interface MyInterface {
  value: string;
}
`

function esFacade(code) {
  const [, , facade] = esParse(code)
  return facade
}

function rsFacade(code) {
  const { output } = parse({
    input: [{ filename: 'index.ts', code }],
  })
  return output[0].facade
}

;(async () => {
  await init

  strictEqual(
    // ↓ `es-module-lexer` does not support direct parsing of TS syntax
    esFacade(``), // true
    rsFacade(sample), // true
  )
})()
```

**Comment by MitchLillie** [comment]
@fz6m - Thank you for the response. It makes sense that `es-module-lexer` does not support ts. However, I still wonder, should the example code really be marked as `facade: true`?

Per the es-module-lexer docs, "Facade modules that only use import / export syntax can be detected via the third return value". So `export * from './file'` is a facade, but `export const foo = "bar"` is not. IMO, type definitions are more like `export const foo = "bar"`.
