### ISSUE TITLE
Does not contain the macOS 64-bit binary  file 

### ISSUE THREAD

**Issue by screetBloom** [fz6m/rs-module-lexer#7]
## Version
rs-module-lexer@2.4.0

## Question

The package @xn-sakina/rml-darwin-x64 distributed on the macOS platform does not contain the file rs-module-lexer.darwin-x64.node.

<img width="355" alt="image" src="https://github.com/user-attachments/assets/d9554a1d-1f12-4c6a-8c15-f209d3b50be7">

>  I'll provide a reproducible repository later

### Reproduction

https://github.com/fz6m/rs-module-lexer

### System Info

```Shell
System:
    OS: macOS 12.0.1
    CPU: (10) x64 Apple M1 Pro
    Memory: 33.94 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.20.1 - ~/.nvm/versions/node/v16.20.1/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.20.1/bin/yarn
    npm: 8.19.4 - ~/.nvm/versions/node/v16.20.1/bin/npm
    pnpm: 8.9.0 - ~/.nvm/versions/node/v16.20.1/bin/pnpm
    bun: 0.7.1 - ~/.bun/bin/bun
  Browsers:
    Chrome: 127.0.6533.99
    Safari: 15.1
```

### Used Package Manager

npm

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by fz6m** [comment]
fixed in `v2.5.0` version
