### ISSUE TITLE
Unable to parse the content of .jsx files with a .js extension.

### ISSUE THREAD

**Issue by screetBloom** [fz6m/rs-module-lexer#9]
### Describe the bug

Unable to parse the content of .jsx files with a .js extension.

I have already provided a minimal reproduction

https://github.com/screetBloom/rs-lexer-reproduction/blob/master/fixtures/jsx/test.js#L393

``` ts
  const { output } = parse({ input: [{ filename, code }] })
                     ^

Error:   × Expression expected
     ╭─[test.js:393:1]
 390 │         navigation = this._navigation;
 391 │       }
 392 │       invariant(navigation, 'failed to get navigation');
 393 │       return <Component {...this.props} navigation={navigation} />;
     ·              ─
 394 │     }
 395 │   }
     ╰────
  × Expected ';', got '{'
     ╭─[test.js:393:1]
 390 │         navigation = this._navigation;
 391 │       }
 392 │       invariant(navigation, 'failed to get navigation');
 393 │       return <Component {...this.props} navigation={navigation} />;
     ·                         ─
 394 │     }
 395 │   }
     ╰────
```

### Reproduction

https://github.com/screetBloom/rs-lexer-reproduction

### System Info

```Shell
System:
    OS: macOS 12.0.1
    CPU: (10) x64 Apple M1 Pro
    Memory: 40.93 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.20.1 - ~/.nvm/versions/node/v16.20.1/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.20.1/bin/yarn
    npm: 8.19.4 - ~/.nvm/versions/node/v16.20.1/bin/npm
    pnpm: 8.9.0 - ~/.nvm/versions/node/v16.20.1/bin/pnpm
    bun: 0.7.1 - ~/.bun/bin/bun
  Browsers:
    Chrome: 127.0.6533.100
    Safari: 15.1
```

### Used Package Manager

pnpm

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by screetBloom** [comment]
I have already resolved it by adding an failed parse, when you have time, you can check if the issue is caused by my usage

**Comment by fz6m** [comment]
`.js` files do not support JSX syntax, like esbuild, you will also get the same error:

```ts
import { transformSync } from 'esbuild'

const run = async () => {
  const res = transformSync(
    `
export const A = () => <div>1</div>
        `,
    {
      loader: 'js',
    },
  )

  // ERROR: The JSX syntax extension is not currently enabled
}

run()
```

To parse very old projects (which might use JSX syntax in `.js` files before the standard was formed), please force set all `.js` files as JSX :

```ts
   const isJS = originFilename.endsWith('.js')
   const filename = isJS ? originFilename.replace(/\.js$/, '.jsx') : originFilename
```
